version: '3'

services:
  ml-dev-ad:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.gpu
    container_name: ml-dev-ad
    image: ml-dev-ad-image
    shm_size: '24gb'
    tty: true
    env_file:
      - .env
    volumes: 
      - $PWD:/workspace
    command: '/bin/bash'
    ports:
      - 18141-18150:18141-18150
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
